# App config
server:
  port: 8080

spring:
  application:
    name: Api Gateway
  cloud:
    gateway:
      routes:
        - id: movieRoute
          uri: lb://movies-service
          predicates:
            - Path=/movies/**

        - id: seriesRoute
          uri: lb://series-service
          predicates:
            - Path=/series/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

#Actuator: Monitoreando la salud de nuestros microservicios
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
info:
  app:
    name: Api Gateway
    description: Enrutamiento, limitación de velocidad, facturación, monitoreo, autenticación, composición de API, políticas, alertas y seguridad.
    version: 1.0.0
